config/routes.rb
Rails.application.routes.draw do
  root 'jorneys#index'
  resources :jorneys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jorney.rb
class Jorney < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jorneys_controller.rb
class JorneysController < ApplicationController
  before_action :set_jorney, only: [:show, :edit, :update, :destroy]

  def index
    @jorneys = Jorney.all
  end


  def show
  end

  def new
    @jorney = Jorney.new
  end

  def create
    @jorney = Jorney.new(jorney_params)
    if @jorney.save
      redirect_to @jorney
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @jorney.update_attributes(jorney_params)
      redirect_to @jorney
    else
      render :edit
    end
  end

  def destroy
    @jorney.destroy
    redirect_to jorneys_path
  end


  private

  def set_jorney
    @jorney = Jorney.find(params[:id])
  end

  def jorney_params
    params.require(:jorney).permit(:title, :capacity, :start_datetime)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jorneys/_form.html.erb
<%= form_for @jorney do |f| %>
   <div class="form-control">
     <%= f.label :title %>
     <%= f.text_field :title %>
   </div>
   <div class="form-control">
     <%= f.label :capacity %>
     <%= f.number_field :capacity %>
   </div>
    <div class="form-control">
     <%= f.label :start_datetime %>
     <%= f.datetime_field :start_datetime %>
   </div>
    <div class="form-control">
      <%= f.submit 'Save' %>
    </div>
<% end %>

app/views/jorneys/edit.html.erb
<h2>Edit jorney</h2>

<%= render 'form' %>

app/views/jorneys/index.html.erb
<h1>Jorneys</h1>



<% @jorneys.each do |jorney| %>
    <h2><%= link_to jorney.title, jorney_path(jorney) %></h2>
<% end %>

app/views/jorneys/new.html.erb
<h2>New Jorney</h2>


<%= render 'form' %>

app/views/jorneys/show.html.erb
<h1><%= @jorney.title %></h1>

<%= link_to 'Edit jorney', edit_jorney_path(@jorney) %>

<%= link_to 'Delete jorney', jorney_path(@jorney), method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pivoraki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= link_to 'All jorneys', jorneys_path %>
  <%= link_to 'New Jorney',  new_jorney_path %>
    <%= yield %>
  </body>
</html>